In [1]:
import pandas as pd
import numpy as np

### Numpy Array Operations

#### stacking of 2 arrays 

In [11]:
a = np.array([[1,2],[3,4]]) 

print('First Array:') 
print(a,'\n') 
b = np.array([[5,6],[7,8]]) 

print('Second Array:')
print(b,'\n')   

print('Stack the two arrays along axis 0:')
print(np.stack((a,b),0),'\n')

print('Stack the two arrays along axis 1:')
print(np.stack((a,b),1))

print('Default stacking:')
print(np.stack((a,b)))

First Array:
[[1 2]
 [3 4]] 

Second Array:
[[5 6]
 [7 8]] 

Stack the two arrays along axis 0:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] 

Stack the two arrays along axis 1:
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]
Default stacking:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [36]:
# list stacking
lst1 = [[1,2],[3,4],[5,6]]
lst2 = [[7,8],[9,10],[11],[12,13,14]]
np.stack(lst1)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [37]:
lst1 + lst2

[[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11], [12, 13, 14]]

In [38]:
lst1.append(lst2)
lst1

[[1, 2], [3, 4], [5, 6], [[7, 8], [9, 10], [11], [12, 13, 14]]]

#### Array Reshaping

In [43]:
# Reshape From 1-D to 2-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [45]:
# Reshape From 1-D to 3-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [47]:
array = np.arange(8)
print("Original array : \n", array)
  
# shape array with 2 rows and 4 columns
array = np.arange(8).reshape(2, 4)
print("\narray reshaped with 2 rows and 4 columns : \n", array)
  
# shape array with 4 rows and 2 columns
array = np.arange(8).reshape(4 ,2)
print("\narray reshaped with 2 rows and 4 columns : \n", array)
  
# Constructs 3D array
array = np.arange(8).reshape(2, 2, 2)
print("\nOriginal array reshaped to 3D : \n", array)

Original array : 
 [0 1 2 3 4 5 6 7]

array reshaped with 2 rows and 4 columns : 
 [[0 1 2 3]
 [4 5 6 7]]

array reshaped with 2 rows and 4 columns : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]

Original array reshaped to 3D : 
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
