In [1]:
import pandas as pd
import numpy as np

### List and Set Operations

In [2]:
final_feat_list = list(set(all_names) - set(cols_to_exclude))

NameError: name 'all_names' is not defined

### Numpy Array Operations

#### stacking of 2 arrays 

In [11]:
a = np.array([[1,2],[3,4]]) 

print('First Array:') 
print(a,'\n') 
b = np.array([[5,6],[7,8]]) 

print('Second Array:')
print(b,'\n')   

print('Stack the two arrays along axis 0:')
print(np.stack((a,b),0),'\n')

print('Stack the two arrays along axis 1:')
print(np.stack((a,b),1))

print('Default stacking:')
print(np.stack((a,b)))

First Array:
[[1 2]
 [3 4]] 

Second Array:
[[5 6]
 [7 8]] 

Stack the two arrays along axis 0:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] 

Stack the two arrays along axis 1:
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]
Default stacking:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [36]:
# list stacking
lst1 = [[1,2],[3,4],[5,6]]
lst2 = [[7,8],[9,10],[11],[12,13,14]]
np.stack(lst1)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [37]:
lst1 + lst2

[[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11], [12, 13, 14]]

In [38]:
lst1.append(lst2)
lst1

[[1, 2], [3, 4], [5, 6], [[7, 8], [9, 10], [11], [12, 13, 14]]]

#### Array Reshaping

In [43]:
# Reshape From 1-D to 2-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [45]:
# Reshape From 1-D to 3-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [47]:
array = np.arange(8)
print("Original array : \n", array)
  
# shape array with 2 rows and 4 columns
array = np.arange(8).reshape(2, 4)
print("\narray reshaped with 2 rows and 4 columns : \n", array)
  
# shape array with 4 rows and 2 columns
array = np.arange(8).reshape(4 ,2)
print("\narray reshaped with 2 rows and 4 columns : \n", array)
  
# Constructs 3D array
array = np.arange(8).reshape(2, 2, 2)
print("\nOriginal array reshaped to 3D : \n", array)

Original array : 
 [0 1 2 3 4 5 6 7]

array reshaped with 2 rows and 4 columns : 
 [[0 1 2 3]
 [4 5 6 7]]

array reshaped with 2 rows and 4 columns : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]

Original array reshaped to 3D : 
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


#### Repeat a sequence (np.repeat and np.tile)

np.repeat: repeats individual elements \n
np.tile: repeats entire sequence

In [54]:
np.repeat(  list(np.arange(0,35,1))  ,3)

array([ 0,  0,  0,  1,  1,  1,  2,  2,  2,  3,  3,  3,  4,  4,  4,  5,  5,
        5,  6,  6,  6,  7,  7,  7,  8,  8,  8,  9,  9,  9, 10, 10, 10, 11,
       11, 11, 12, 12, 12, 13, 13, 13, 14, 14, 14, 15, 15, 15, 16, 16, 16,
       17, 17, 17, 18, 18, 18, 19, 19, 19, 20, 20, 20, 21, 21, 21, 22, 22,
       22, 23, 23, 23, 24, 24, 24, 25, 25, 25, 26, 26, 26, 27, 27, 27, 28,
       28, 28, 29, 29, 29, 30, 30, 30, 31, 31, 31, 32, 32, 32, 33, 33, 33,
       34, 34, 34])

In [72]:
an_array = np.array([1,2,3])
repeats_array = np.tile(an_array, 3)
repeats_array_1 = np.tile(an_array, (5,1))

print('array:',an_array,
      '\n repeated array:',repeats_array,
     '\n repeated array:\n',repeats_array_1)

array: [1 2 3] 
 repeated array: [1 2 3 1 2 3 1 2 3] 
 repeated array:
 [[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


### Pandas

#### melt:  wide to long

melt: to change the DataFrame format from wide to long, column names are stored in 'variable' column and values are stored in 'value' column 

In [75]:
d1 = {"Name": ["Pankaj", "Lisa", "David"], 
      "ID": [1, 2, 3], 
      "Role": ["CEO", "Editor", "Author"],
      "Salary":[50000,20000,30000]}

df = pd.DataFrame(d1)

print(df,'\n')

df_melted = pd.melt(df, id_vars=["ID"], value_vars=["Name", "Role","Salary"])

print(df_melted)

     Name  ID    Role  Salary
0  Pankaj   1     CEO   50000
1    Lisa   2  Editor   20000
2   David   3  Author   30000 

   ID variable   value
0   1     Name  Pankaj
1   2     Name    Lisa
2   3     Name   David
3   1     Role     CEO
4   2     Role  Editor
5   3     Role  Author
6   1   Salary   50000
7   2   Salary   20000
8   3   Salary   30000


In [79]:
# Multiple Columns as id_vars
df_melted_1 = pd.melt(df, id_vars=["ID","Name"], value_vars=["Role","Salary"], var_name="Attribute", value_name="Value")
df_melted_1

ID    Name Attribute   Value
0   1  Pankaj      Role     CEO
1   2    Lisa      Role  Editor
2   3   David      Role  Author
3   1  Pankaj    Salary   50000
4   2    Lisa    Salary   20000
5   3   David    Salary   30000

#### Pivot: Unmelting DataFrame using pivot() function

pivot() function to unmelt a DataFrame object and get the original dataframe. The pivot() function ‘index’ parameter value should be same as the ‘id_vars’ value. The ‘columns’ value should be passed as the name of the ‘variable’ column.

In [105]:
df_unmelted = df_melted.pivot(index='ID', columns='variable')
print(df_unmelted,'\n')

print(df_unmelted.reset_index())

           value               
variable    Name    Role Salary
ID                             
1         Pankaj     CEO  50000
2           Lisa  Editor  20000
3          David  Author  30000 

         ID   value               
variable       Name    Role Salary
0         1  Pankaj     CEO  50000
1         2    Lisa  Editor  20000
2         3   David  Author  30000


In [106]:
df_unmelted = df_unmelted['value'].reset_index()
df_unmelted.columns.name = None
print(df_unmelted)

   ID    Name    Role Salary
0   1  Pankaj     CEO  50000
1   2    Lisa  Editor  20000
2   3   David  Author  30000


#### pivot_table

In [125]:
df_melted

ID variable   value
0   1     Name  Pankaj
1   2     Name    Lisa
2   3     Name   David
3   1     Role     CEO
4   2     Role  Editor
5   3     Role  Author
6   1   Salary   50000
7   2   Salary   20000
8   3   Salary   30000

In [129]:
pd.pivot_table(df_melted, values='ID', index=['variable'],
                    columns=['variable'], aggfunc=np.sum).reset_index()

variable variable  Name  Role  Salary
0            Name   6.0   NaN     NaN
1            Role   NaN   6.0     NaN
2          Salary   NaN   NaN     6.0

#### Sorting

In [101]:
df_unmelted.sort_values(by=['Salary']).reset_index(drop=True)

ID    Name    Role Salary
0   2    Lisa  Editor  20000
1   3   David  Author  30000
2   1  Pankaj     CEO  50000

#### map

In [108]:
role_map={'Editor':0,
            'Authory':1,
            'CEO':2}

inv_role_map = {v: k for k, v in role_map.items()}
inv_role_map

{0: 'Editor', 1: 'Authory', 2: 'CEO'}

In [111]:
df_unmelted['Role'].astype('int').map(inv_role_map)

ValueError: invalid literal for int() with base 10: 'CEO'

#### print df rows by index

In [132]:
df_unmelted

ID    Name    Role Salary
0   1  Pankaj     CEO  50000
1   2    Lisa  Editor  20000
2   3   David  Author  30000

In [133]:
print(df_unmelted.loc[[2]])

   ID   Name    Role Salary
2   3  David  Author  30000


#### select/remove columns

In [137]:
cols_to_rm = ['Role','Salary']
df_removed_cols = df_unmelted.drop(cols_to_rm, axis=1)
df_removed_cols

ID    Name
0   1  Pankaj
1   2    Lisa
2   3   David

In [138]:
cols_to_select = ['ID','Name']
df_selected_cols = df_unmelted[cols_to_select]
df_selected_cols

ID    Name
0   1  Pankaj
1   2    Lisa
2   3   David

#### repeat and append dataframe

#### group by and count

#### Concat and appending

### Modelling

In [1]:
import pandas as pd
import numpy as np 
from sklearn.model_selection import train_test_split

from sklearn.model_selection import KFold,StratifiedKFold
from sklearn.metrics import f1_score,precision_score, confusion_matrix
from sklearn.metrics import auc, roc_auc_score, roc_curve,precision_recall_curve, accuracy_score, f1_score

from xgboost import XGBRegressor
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier
from sklearn.linear_model import LogisticRegression

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
pd.set_option('display.max_columns',None)

In [ ]:
# getting index of categorical features
cat_feat_list = ['Accomodation_Type','Reco_Policy_Cat','Region_Code',
                'City_Code','Health_Indicator','Is_Spouse',
                'is_policy_holder','Holding_Policy_Type','Reco_Insurance_Type']

categorical_features_indices = []
for i in range(len(final_feat_list)):
    if final_feat_list[i] in cat_feat_list:
        print(final_feat_list[i],'\n')
        categorical_features_indices.append(i)

In [ ]:
# train-test split (70-30)
X_train,X_test,y_train,y_test=train_test_split(df_train[final_feat_list],
                                               df_train[label],
                                               stratify=df_train[label],
                                               test_size=0.3,
                                               random_state=984)

In [ ]:
#K-fold cross validation 
errcb=[]
y_pred_totcb=[]
fold=StratifiedKFold(n_splits=20,shuffle=True,random_state=1994)
i=1
for train_index, test_index in fold.split(X,y):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y[train_index], y[test_index]
    m=CatBoostClassifier(n_estimators=3000,random_state=1994,eval_metric='AUC',max_depth=6,learning_rate=0.133,od_wait=50
                     ,l2_leaf_reg=10,cat_features=categorical_features_indices,bagging_temperature=0.85,random_strength=100,
                     use_best_model=True)
    m.fit(X_train,y_train,eval_set=[(X_train,y_train),(X_test, y_test)], early_stopping_rounds=100,verbose=100)
    preds=m.predict_proba(X_test)[:,-1]
    print("err: ",roc_auc_score(y_test,preds))
    errcb.append(roc_auc_score(y_test,preds))
    p = m.predict_proba(df_test[final_feat_list])[:,-1]
    y_pred_totcb.append(p)
    
df_test['Response']= np.mean(y_pred_totcb,0)

In [ ]:
#LightGBM Binary Classifcation
X_train,X_test,y_train,y_test=train_test_split(df_train[final_feat_list],
                                               df_train[label],
                                               stratify=df_train[label],
                                               test_size=0.3,
                                               random_state=984)


lgbc=LGBMClassifier(n_estimators=7000,\
                   learning_rate=0.1,\
                    max_depth  =10,
                   num_leaves=32)

lgbc.fit(X_train, np.where(y_train==0,0,1),\
        eval_set=[(X_test, np.where(y_test==0,0,1))], early_stopping_rounds=200,\
         verbose=300)

train_probs = lgbc.predict_proba(X_train, num_iteration=lgbc.best_iteration_)[:,1]
test_probs = lgbc.predict_proba(X_test, num_iteration=lgbc.best_iteration_)[:,1]
print(f'Train AUC: {np.round(roc_auc_score(np.where(y_train==0,0,1), train_probs),4)}, Test AUC: {np.round(roc_auc_score(np.where(y_test==0,0,1), test_probs),4)}')
##

In [ ]:
def Find_Optimal_Cutoff(target, predicted):
    fpr, tpr, threshold = roc_curve(target, predicted)
    i = np.arange(len(tpr)) 
    roc = pd.DataFrame({'tf' : pd.Series(tpr-(1-fpr), index=i), 'threshold' : pd.Series(threshold, index=i)})
    roc_t = roc.iloc[(roc.tf-0).abs().argsort()[:1]]

    return list(roc_t['threshold']) 


precision, recall, thresholds = precision_recall_curve(np.where(y_test==0,0,1), test_probs)
f1_scores = 2*recall*precision/(recall+precision)
thr=thresholds[np.argmax(f1_scores)]
print('Best threshold: ',thr )

thr2=Find_Optimal_Cutoff(np.where(y_test==0,0,1), test_probs)
thr2

In [ ]:
#training the model
lgbc=LGBMClassifier(n_estimators=424,\
                   learning_rate=0.1,\
                    max_depth  =10,
                   num_leaves=32)

lgbc.fit(df_train[final_feat_list], df_train[label])

#prediction on the test dataset
y_pred_1=lgbc.predict_proba(df_test[final_feat_list])[:,1]

In [ ]:
sub=df_test.sort_values(by=['id','pred','pred_abs'],ascending=[True,False,False]).reset_index(drop=True).groupby('id').first().reset_index()