In [1]:
import pandas as pd
import numpy as np

#### Numpy Array Operations

In [11]:
import numpy as np 
a = np.array([[1,2],[3,4]]) 

print('First Array:') 
print(a,'\n') 
b = np.array([[5,6],[7,8]]) 

print('Second Array:')
print(b,'\n')   

print('Stack the two arrays along axis 0:')
print(np.stack((a,b),0),'\n')

print('Stack the two arrays along axis 1:')
print(np.stack((a,b),1))

print('Default stacking:')
print(np.stack((a,b)))

First Array:
[[1 2]
 [3 4]] 

Second Array:
[[5 6]
 [7 8]] 

Stack the two arrays along axis 0:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] 

Stack the two arrays along axis 1:
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]
Default stacking:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [15]:
a.shape

(2, 2)